# Generated by Django 4.1.6 on 2023-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
