# Generated by Django 4.1.6 on 2023-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
